---
- name: Installations
  hosts: localhost
  connection: local
  tasks:
    - ansible.builtin.debug:
        msg: Begin Brew Install
    - name: Include Brew Install
      ansible.builtin.include_tasks:
        file: brew-install.yaml
    - ansible.builtin.debug:
        msg: End Brew Install
