---

- name: Installations
  hosts: localhost 
  connection: local

  tasks:
   - name: Brew Install Git
     community.general.homebrew:
       name: git
       state: present

   - name: Brew Install Neovim
     community.general.homebrew:
       name: neovim
       state: present

   - name: Brew Install Fzf
     community.general.homebrew:
       name: fzf
       state: present

   - name: Brew Install Ripgrep
     community.general.homebrew:
       name: ripgrep
       state: present

   - name: Brew Install Fd
     community.general.homebrew:
       name: fd
       state: present

   - name: Brew Install zoxide
     community.general.homebrew:
       name: zoxide
       state: present

   - name: Brew Install tmux
     community.general.homebrew:
       name: tmux
       state: present
       
   - name: Brew Install oh-my-posh
     community.general.homebrew:
       name: oh-my-posh
       state: present

   - name: Brew Install mise
     community.general.homebrew:
       name: mise
       state: present

   - name: Brew Install Fire Code Nerd Font
     community.general.homebrew_cask:
       name: font-fira-code-nerd-font
       state: present

   - name: Brew Install Kitty
     community.general.homebrew_cask:
       name: kitty
       state: present

   - name: Brew Install Raycast
     community.general.homebrew_cask:
       name: raycast
       state: present

   - name: Brew Install 1Password
     community.general.homebrew_cask:
       name: 1password
       state: present
